version: "2"
run:
  concurrency: 4
  tests: true
linters:
  enable:
    - bodyclose
    - gocritic
    - gosec
    - makezero
    - misspell
    - modernize
    - nakedret
    - revive
    - errcheck
    - staticcheck
    - govet
    - ineffassign
    - intrange
    - unused
    - usetesting
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
      - internal/githubv4mock
    rules:
      - linters:
          - revive
        text: "var-naming: avoid package names that conflict with Go standard library package names"
  settings:
    staticcheck:
      checks:
        - "all"
        - -QF1008
        - -ST1000
    usetesting:
      context-background: true
      context-todo: true
      os-chdir: true
      os-mkdir-temp: true
      os-setenv: true
      os-create-temp: true
      os-temp-dir: true
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
