// Code generated by mcpgen. DO NOT EDIT.

package github

import (
	"github.com/google/jsonschema-go/jsonschema"
)

// SearchRepositoriesInput schema variables (generated)
var (
	_searchrepositoriesinputSchema = &jsonschema.Schema{
		Type: "object",
		Properties: map[string]*jsonschema.Schema{
			"query": {
				Type:        "string",
				Description: "Repository search query using GitHub search syntax",
			},
			"sort": {
				Type:        "string",
				Description: "Sort repositories by field - defaults to best match",
				Enum:        []any{"stars", "forks", "help-wanted-issues", "updated"},
			},
			"order": {
				Type:        "string",
				Description: "Sort order (asc/desc)",
				Enum:        []any{"asc", "desc"},
			},
			"minimal_output": {
				Type:        "boolean",
				Description: "Return minimal repository information - when false returns full GitHub API objects",
			},
			"page": {
				Type:        "integer",
				Description: "Page number for pagination (min 1)",
			},
			"perPage": {
				Type:        "integer",
				Description: "Results per page for pagination (min 1 and max 100)",
			},
		},
		Required: []string{
			"query",
		},
		AdditionalProperties: &jsonschema.Schema{Not: &jsonschema.Schema{}},
	}
	_searchrepositoriesinputResolved, _ = _searchrepositoriesinputSchema.Resolve(nil)
)

// MCPSchema returns the pre-computed JSON schema for SearchRepositoriesInput.
// This implements mcp.SchemaProvider.
func (SearchRepositoriesInput) MCPSchema() *jsonschema.Schema {
	return _searchrepositoriesinputSchema
}

// MCPResolvedSchema returns the pre-resolved JSON schema for SearchRepositoriesInput.
// This implements mcp.ResolvedSchemaProvider.
func (SearchRepositoriesInput) MCPResolvedSchema() *jsonschema.Resolved {
	return _searchrepositoriesinputResolved
}

// SearchCodeInput schema variables (generated)
var (
	_searchcodeinputSchema = &jsonschema.Schema{
		Type: "object",
		Properties: map[string]*jsonschema.Schema{
			"query": {
				Type:        "string",
				Description: "Search query using GitHub code search syntax",
			},
			"sort": {
				Type:        "string",
				Description: "Sort field (indexed only)",
			},
			"order": {
				Type:        "string",
				Description: "Sort order for results (asc/desc)",
				Enum:        []any{"asc", "desc"},
			},
			"page": {
				Type:        "integer",
				Description: "Page number for pagination (min 1)",
			},
			"perPage": {
				Type:        "integer",
				Description: "Results per page for pagination (min 1 and max 100)",
			},
		},
		Required: []string{
			"query",
		},
		AdditionalProperties: &jsonschema.Schema{Not: &jsonschema.Schema{}},
	}
	_searchcodeinputResolved, _ = _searchcodeinputSchema.Resolve(nil)
)

// MCPSchema returns the pre-computed JSON schema for SearchCodeInput.
// This implements mcp.SchemaProvider.
func (SearchCodeInput) MCPSchema() *jsonschema.Schema {
	return _searchcodeinputSchema
}

// MCPResolvedSchema returns the pre-resolved JSON schema for SearchCodeInput.
// This implements mcp.ResolvedSchemaProvider.
func (SearchCodeInput) MCPResolvedSchema() *jsonschema.Resolved {
	return _searchcodeinputResolved
}

// SearchUsersInput schema variables (generated)
var (
	_searchusersinputSchema = &jsonschema.Schema{
		Type: "object",
		Properties: map[string]*jsonschema.Schema{
			"query": {
				Type:        "string",
				Description: "User search query using GitHub search syntax",
			},
			"sort": {
				Type:        "string",
				Description: "Sort users by followers/repositories/joined",
				Enum:        []any{"followers", "repositories", "joined"},
			},
			"order": {
				Type:        "string",
				Description: "Sort order (asc/desc)",
				Enum:        []any{"asc", "desc"},
			},
			"page": {
				Type:        "integer",
				Description: "Page number for pagination (min 1)",
			},
			"perPage": {
				Type:        "integer",
				Description: "Results per page for pagination (min 1 and max 100)",
			},
		},
		Required: []string{
			"query",
		},
		AdditionalProperties: &jsonschema.Schema{Not: &jsonschema.Schema{}},
	}
	_searchusersinputResolved, _ = _searchusersinputSchema.Resolve(nil)
)

// MCPSchema returns the pre-computed JSON schema for SearchUsersInput.
// This implements mcp.SchemaProvider.
func (SearchUsersInput) MCPSchema() *jsonschema.Schema {
	return _searchusersinputSchema
}

// MCPResolvedSchema returns the pre-resolved JSON schema for SearchUsersInput.
// This implements mcp.ResolvedSchemaProvider.
func (SearchUsersInput) MCPResolvedSchema() *jsonschema.Resolved {
	return _searchusersinputResolved
}

// GetFileContentsInput schema variables (generated)
var (
	_getfilecontentsinputSchema = &jsonschema.Schema{
		Type: "object",
		Properties: map[string]*jsonschema.Schema{
			"owner": {
				Type:        "string",
				Description: "Repository owner (username or organization)",
			},
			"repo": {
				Type:        "string",
				Description: "Repository name",
			},
			"path": {
				Type:        "string",
				Description: "Path to file or directory",
			},
			"ref": {
				Type:        "string",
				Description: "Git ref such as branch name or tag name or commit SHA",
			},
			"sha": {
				Type:        "string",
				Description: "Commit SHA (overrides ref if specified)",
			},
		},
		Required: []string{
			"owner",
			"repo",
		},
		AdditionalProperties: &jsonschema.Schema{Not: &jsonschema.Schema{}},
	}
	_getfilecontentsinputResolved, _ = _getfilecontentsinputSchema.Resolve(nil)
)

// MCPSchema returns the pre-computed JSON schema for GetFileContentsInput.
// This implements mcp.SchemaProvider.
func (GetFileContentsInput) MCPSchema() *jsonschema.Schema {
	return _getfilecontentsinputSchema
}

// MCPResolvedSchema returns the pre-resolved JSON schema for GetFileContentsInput.
// This implements mcp.ResolvedSchemaProvider.
func (GetFileContentsInput) MCPResolvedSchema() *jsonschema.Resolved {
	return _getfilecontentsinputResolved
}

// CreateIssueInput schema variables (generated)
var (
	_createissueinputSchema = &jsonschema.Schema{
		Type: "object",
		Properties: map[string]*jsonschema.Schema{
			"owner": {
				Type:        "string",
				Description: "Repository owner",
			},
			"repo": {
				Type:        "string",
				Description: "Repository name",
			},
			"title": {
				Type:        "string",
				Description: "Issue title",
			},
			"body": {
				Type:        "string",
				Description: "Issue body content",
			},
			"assignees": {
				Type:        "array",
				Description: "Usernames to assign to this issue",
			},
			"labels": {
				Type:        "array",
				Description: "Labels to add to this issue",
			},
			"milestone": {
				Type:        "integer",
				Description: "Milestone number to assign",
			},
		},
		Required: []string{
			"owner",
			"repo",
			"title",
		},
		AdditionalProperties: &jsonschema.Schema{Not: &jsonschema.Schema{}},
	}
	_createissueinputResolved, _ = _createissueinputSchema.Resolve(nil)
)

// MCPSchema returns the pre-computed JSON schema for CreateIssueInput.
// This implements mcp.SchemaProvider.
func (CreateIssueInput) MCPSchema() *jsonschema.Schema {
	return _createissueinputSchema
}

// MCPResolvedSchema returns the pre-resolved JSON schema for CreateIssueInput.
// This implements mcp.ResolvedSchemaProvider.
func (CreateIssueInput) MCPResolvedSchema() *jsonschema.Resolved {
	return _createissueinputResolved
}

// CreatePullRequestInput schema variables (generated)
var (
	_createpullrequestinputSchema = &jsonschema.Schema{
		Type: "object",
		Properties: map[string]*jsonschema.Schema{
			"owner": {
				Type:        "string",
				Description: "Repository owner",
			},
			"repo": {
				Type:        "string",
				Description: "Repository name",
			},
			"title": {
				Type:        "string",
				Description: "Pull request title",
			},
			"body": {
				Type:        "string",
				Description: "Pull request body/description",
			},
			"head": {
				Type:        "string",
				Description: "Branch where your changes are implemented",
			},
			"base": {
				Type:        "string",
				Description: "Branch you want the changes pulled into",
			},
			"draft": {
				Type:        "boolean",
				Description: "Create as a draft pull request",
			},
			"maintainer_can_modify": {
				Type:        "boolean",
				Description: "Whether maintainers can modify the pull request",
			},
		},
		Required: []string{
			"owner",
			"repo",
			"title",
			"head",
			"base",
		},
		AdditionalProperties: &jsonschema.Schema{Not: &jsonschema.Schema{}},
	}
	_createpullrequestinputResolved, _ = _createpullrequestinputSchema.Resolve(nil)
)

// MCPSchema returns the pre-computed JSON schema for CreatePullRequestInput.
// This implements mcp.SchemaProvider.
func (CreatePullRequestInput) MCPSchema() *jsonschema.Schema {
	return _createpullrequestinputSchema
}

// MCPResolvedSchema returns the pre-resolved JSON schema for CreatePullRequestInput.
// This implements mcp.ResolvedSchemaProvider.
func (CreatePullRequestInput) MCPResolvedSchema() *jsonschema.Resolved {
	return _createpullrequestinputResolved
}
