package github

import (
	"embed"
)

// UIAssets embeds built MCP App UI HTML 文件s.
// 这些文件s are generated by running `script/build-ui` which compiles
// React/Primer components 在ui/ directory.
//
//go:embed ui_dist/*.html
var UIAssets embed.FS

// GetUIAsset 读取s 一个UI asset 来自embedded 文件system.
// name 应当是 just 文件name (e.g., "获取-me.html").
func GetUIAsset(name string) (string, error) {
	data, err := UIAssets.ReadFile("ui_dist/" + name)
	if err != nil {
		return "", err
	}
	return string(data), nil
}

// MustGetUIAsset 读取s 一个UI asset 和panics if it fails.
// Use this 当asset is 必需 f或服务器 operation.
func MustGetUIAsset(name string) string {
	html, err := GetUIAsset(name)
	if err != nil {
		panic("failed to load UI asset " + name + ": " + err.Error())
	}
	return html
}

// UIAssetsAvailable 返回 真 如果MCP App UI assets have been built.
// 此检查s f或一个known UI asset 文件 to determine if `script/build-ui` has been run.
// Use this to gracefully skip UI registration when assets aren't available,
// allowing non-UI features to work without requiring 一个UI build.
func UIAssetsAvailable() bool {
	_, err := GetUIAsset("get-me.html")
	return err == nil
}
