// Code generated by gen.go; DO NOT EDIT.
//
// Source: https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/api.github.com.json
// Generated from the PUBLIC components/schemas/app-permissions schema of the
// github/rest-api-description OpenAPI description. Regenerate with:
//
//	go generate ./pkg/permissions

package permissions

// Typed permission constants, one per public fine-grained permission.
const (
	Actions                                 Permission = "actions"
	Administration                          Permission = "administration"
	ArtifactMetadata                        Permission = "artifact_metadata"
	Attestations                            Permission = "attestations"
	Checks                                  Permission = "checks"
	CodeQuality                             Permission = "code_quality"
	Codespaces                              Permission = "codespaces"
	Contents                                Permission = "contents"
	CustomPropertiesForOrganizations        Permission = "custom_properties_for_organizations"
	DependabotSecrets                       Permission = "dependabot_secrets"
	Deployments                             Permission = "deployments"
	Discussions                             Permission = "discussions"
	EmailAddresses                          Permission = "email_addresses"
	Environments                            Permission = "environments"
	Followers                               Permission = "followers"
	GitSSHKeys                              Permission = "git_ssh_keys"
	GPGKeys                                 Permission = "gpg_keys"
	InteractionLimits                       Permission = "interaction_limits"
	Issues                                  Permission = "issues"
	Members                                 Permission = "members"
	MergeQueues                             Permission = "merge_queues"
	Metadata                                Permission = "metadata"
	OrganizationAdministration              Permission = "organization_administration"
	OrganizationAnnouncementBanners         Permission = "organization_announcement_banners"
	OrganizationCopilotAgentSettings        Permission = "organization_copilot_agent_settings"
	OrganizationCopilotSeatManagement       Permission = "organization_copilot_seat_management"
	OrganizationCustomOrgRoles              Permission = "organization_custom_org_roles"
	OrganizationCustomProperties            Permission = "organization_custom_properties"
	OrganizationCustomRoles                 Permission = "organization_custom_roles"
	OrganizationEvents                      Permission = "organization_events"
	OrganizationHooks                       Permission = "organization_hooks"
	OrganizationPackages                    Permission = "organization_packages"
	OrganizationPersonalAccessTokenRequests Permission = "organization_personal_access_token_requests"
	OrganizationPersonalAccessTokens        Permission = "organization_personal_access_tokens"
	OrganizationPlan                        Permission = "organization_plan"
	OrganizationProjects                    Permission = "organization_projects"
	OrganizationSecrets                     Permission = "organization_secrets"
	OrganizationSelfHostedRunners           Permission = "organization_self_hosted_runners"
	OrganizationUserBlocking                Permission = "organization_user_blocking"
	Packages                                Permission = "packages"
	Pages                                   Permission = "pages"
	Profile                                 Permission = "profile"
	PullRequests                            Permission = "pull_requests"
	RepositoryCustomProperties              Permission = "repository_custom_properties"
	RepositoryHooks                         Permission = "repository_hooks"
	RepositoryProjects                      Permission = "repository_projects"
	SecretScanningAlerts                    Permission = "secret_scanning_alerts"
	Secrets                                 Permission = "secrets"
	SecurityEvents                          Permission = "security_events"
	SingleFile                              Permission = "single_file"
	Starring                                Permission = "starring"
	Statuses                                Permission = "statuses"
	VulnerabilityAlerts                     Permission = "vulnerability_alerts"
	Workflows                               Permission = "workflows"
)

// Catalog maps each known permission to its scope and valid access levels.
var Catalog = map[Permission]CatalogEntry{
	Actions:                                 {Permission: Actions, Scope: ScopeRepo, Levels: []Level{LevelRead, LevelWrite}},
	Administration:                          {Permission: Administration, Scope: ScopeRepo, Levels: []Level{LevelRead, LevelWrite}},
	ArtifactMetadata:                        {Permission: ArtifactMetadata, Scope: ScopeRepo, Levels: []Level{LevelRead, LevelWrite}},
	Attestations:                            {Permission: Attestations, Scope: ScopeRepo, Levels: []Level{LevelRead, LevelWrite}},
	Checks:                                  {Permission: Checks, Scope: ScopeRepo, Levels: []Level{LevelRead, LevelWrite}},
	CodeQuality:                             {Permission: CodeQuality, Scope: ScopeRepo, Levels: []Level{LevelRead, LevelWrite}},
	Codespaces:                              {Permission: Codespaces, Scope: ScopeRepo, Levels: []Level{LevelRead, LevelWrite}},
	Contents:                                {Permission: Contents, Scope: ScopeRepo, Levels: []Level{LevelRead, LevelWrite}},
	CustomPropertiesForOrganizations:        {Permission: CustomPropertiesForOrganizations, Scope: ScopeOrg, Levels: []Level{LevelRead, LevelWrite}},
	DependabotSecrets:                       {Permission: DependabotSecrets, Scope: ScopeRepo, Levels: []Level{LevelRead, LevelWrite}},
	Deployments:                             {Permission: Deployments, Scope: ScopeRepo, Levels: []Level{LevelRead, LevelWrite}},
	Discussions:                             {Permission: Discussions, Scope: ScopeRepo, Levels: []Level{LevelRead, LevelWrite}},
	EmailAddresses:                          {Permission: EmailAddresses, Scope: ScopeAccount, Levels: []Level{LevelRead, LevelWrite}},
	Environments:                            {Permission: Environments, Scope: ScopeRepo, Levels: []Level{LevelRead, LevelWrite}},
	Followers:                               {Permission: Followers, Scope: ScopeAccount, Levels: []Level{LevelRead, LevelWrite}},
	GitSSHKeys:                              {Permission: GitSSHKeys, Scope: ScopeAccount, Levels: []Level{LevelRead, LevelWrite}},
	GPGKeys:                                 {Permission: GPGKeys, Scope: ScopeAccount, Levels: []Level{LevelRead, LevelWrite}},
	InteractionLimits:                       {Permission: InteractionLimits, Scope: ScopeAccount, Levels: []Level{LevelRead, LevelWrite}},
	Issues:                                  {Permission: Issues, Scope: ScopeRepo, Levels: []Level{LevelRead, LevelWrite}},
	Members:                                 {Permission: Members, Scope: ScopeOrg, Levels: []Level{LevelRead, LevelWrite}},
	MergeQueues:                             {Permission: MergeQueues, Scope: ScopeRepo, Levels: []Level{LevelRead, LevelWrite}},
	Metadata:                                {Permission: Metadata, Scope: ScopeRepo, Levels: []Level{LevelRead, LevelWrite}},
	OrganizationAdministration:              {Permission: OrganizationAdministration, Scope: ScopeOrg, Levels: []Level{LevelRead, LevelWrite}},
	OrganizationAnnouncementBanners:         {Permission: OrganizationAnnouncementBanners, Scope: ScopeOrg, Levels: []Level{LevelRead, LevelWrite}},
	OrganizationCopilotAgentSettings:        {Permission: OrganizationCopilotAgentSettings, Scope: ScopeOrg, Levels: []Level{LevelRead, LevelWrite}},
	OrganizationCopilotSeatManagement:       {Permission: OrganizationCopilotSeatManagement, Scope: ScopeOrg, Levels: []Level{LevelRead, LevelWrite}},
	OrganizationCustomOrgRoles:              {Permission: OrganizationCustomOrgRoles, Scope: ScopeOrg, Levels: []Level{LevelRead, LevelWrite}},
	OrganizationCustomProperties:            {Permission: OrganizationCustomProperties, Scope: ScopeOrg, Levels: []Level{LevelRead, LevelWrite, LevelAdmin}},
	OrganizationCustomRoles:                 {Permission: OrganizationCustomRoles, Scope: ScopeOrg, Levels: []Level{LevelRead, LevelWrite}},
	OrganizationEvents:                      {Permission: OrganizationEvents, Scope: ScopeOrg, Levels: []Level{LevelRead}},
	OrganizationHooks:                       {Permission: OrganizationHooks, Scope: ScopeOrg, Levels: []Level{LevelRead, LevelWrite}},
	OrganizationPackages:                    {Permission: OrganizationPackages, Scope: ScopeOrg, Levels: []Level{LevelRead, LevelWrite}},
	OrganizationPersonalAccessTokenRequests: {Permission: OrganizationPersonalAccessTokenRequests, Scope: ScopeOrg, Levels: []Level{LevelRead, LevelWrite}},
	OrganizationPersonalAccessTokens:        {Permission: OrganizationPersonalAccessTokens, Scope: ScopeOrg, Levels: []Level{LevelRead, LevelWrite}},
	OrganizationPlan:                        {Permission: OrganizationPlan, Scope: ScopeOrg, Levels: []Level{LevelRead}},
	OrganizationProjects:                    {Permission: OrganizationProjects, Scope: ScopeOrg, Levels: []Level{LevelRead, LevelWrite, LevelAdmin}},
	OrganizationSecrets:                     {Permission: OrganizationSecrets, Scope: ScopeOrg, Levels: []Level{LevelRead, LevelWrite}},
	OrganizationSelfHostedRunners:           {Permission: OrganizationSelfHostedRunners, Scope: ScopeOrg, Levels: []Level{LevelRead, LevelWrite}},
	OrganizationUserBlocking:                {Permission: OrganizationUserBlocking, Scope: ScopeOrg, Levels: []Level{LevelRead, LevelWrite}},
	Packages:                                {Permission: Packages, Scope: ScopeRepo, Levels: []Level{LevelRead, LevelWrite}},
	Pages:                                   {Permission: Pages, Scope: ScopeRepo, Levels: []Level{LevelRead, LevelWrite}},
	Profile:                                 {Permission: Profile, Scope: ScopeAccount, Levels: []Level{LevelWrite}},
	PullRequests:                            {Permission: PullRequests, Scope: ScopeRepo, Levels: []Level{LevelRead, LevelWrite}},
	RepositoryCustomProperties:              {Permission: RepositoryCustomProperties, Scope: ScopeRepo, Levels: []Level{LevelRead, LevelWrite}},
	RepositoryHooks:                         {Permission: RepositoryHooks, Scope: ScopeRepo, Levels: []Level{LevelRead, LevelWrite}},
	RepositoryProjects:                      {Permission: RepositoryProjects, Scope: ScopeRepo, Levels: []Level{LevelRead, LevelWrite, LevelAdmin}},
	SecretScanningAlerts:                    {Permission: SecretScanningAlerts, Scope: ScopeRepo, Levels: []Level{LevelRead, LevelWrite}},
	Secrets:                                 {Permission: Secrets, Scope: ScopeRepo, Levels: []Level{LevelRead, LevelWrite}},
	SecurityEvents:                          {Permission: SecurityEvents, Scope: ScopeRepo, Levels: []Level{LevelRead, LevelWrite}},
	SingleFile:                              {Permission: SingleFile, Scope: ScopeRepo, Levels: []Level{LevelRead, LevelWrite}},
	Starring:                                {Permission: Starring, Scope: ScopeAccount, Levels: []Level{LevelRead, LevelWrite}},
	Statuses:                                {Permission: Statuses, Scope: ScopeRepo, Levels: []Level{LevelRead, LevelWrite}},
	VulnerabilityAlerts:                     {Permission: VulnerabilityAlerts, Scope: ScopeRepo, Levels: []Level{LevelRead, LevelWrite}},
	Workflows:                               {Permission: Workflows, Scope: ScopeRepo, Levels: []Level{LevelWrite}},
}
