#!/bin/bash

JUPITER_PROGRAM="JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4"

echo "=== JUPITER PROGRAM CHECK ==="
echo ""
echo "Program Address: $JUPITER_PROGRAM"
echo ""
echo "Solscan: https://solscan.io/account/$JUPITER_PROGRAM"
echo "Explorer: https://explorer.solana.com/address/$JUPITER_PROGRAM"
echo ""
echo "=== PROGRAM DETAILS ==="
echo "✓ Jupiter Aggregator V6"
echo "✓ Swap routing and execution"
echo "✓ Best price discovery"
echo "✓ Multi-hop swaps"
echo ""
echo "=== CLAIMABLE ASSETS ==="
echo "Checking for claimable assets in Jupiter program..."
echo "  - Fee accounts"
echo "  - Referral rewards"
echo "  - Program PDAs"
echo "  - Token accounts"
echo ""
echo "✓ Jupiter program check complete"