#!/bin/bash

echo "=== REAL SOLANA DEPLOYMENT GUIDE ==="
echo ""
echo "⚠️  Current Environment: Solana CLI and Rust NOT installed"
echo ""

echo "=== STEP 1: Install Solana CLI ==="
echo ""
echo "sh -c \"\$(curl -sSfL https://release.solana.com/stable/install)\""
echo ""

echo "=== STEP 2: Install Rust ==="
echo ""
echo "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh"
echo ""

echo "=== STEP 3: Configure Solana ==="
echo ""
echo "# Set to mainnet"
echo "solana config set --url https://api.mainnet-beta.solana.com"
echo ""
echo "# Or use Helius"
echo "solana config set --url https://mainnet.helius-rpc.com/?api-key=YOUR_KEY"
echo ""
echo "# Set keypair"
echo "solana config set --keypair ~/.config/solana/id.json"
echo ""

echo "=== STEP 4: Check Balance ==="
echo ""
echo "solana balance"
echo "# Need at least 5 SOL for deployment"
echo ""

echo "=== STEP 5: Build Pentacle Program ==="
echo ""
echo "cd Deployer-Gene/pentacle"
echo "cargo build-bpf"
echo ""

echo "=== STEP 6: Deploy Program ==="
echo ""
echo "solana program deploy target/deploy/pentacle.so"
echo ""
echo "# This will output:"
echo "# Program Id: <PROGRAM_ID>"
echo ""

echo "=== STEP 7: Set Upgrade Authority ==="
echo ""
echo "CONTROLLER=5kDqr3kwfeLhz5rS9cb14Tj2ZZPSq7LddVsxYDV8DnUm"
echo "solana program set-upgrade-authority <PROGRAM_ID> \$CONTROLLER"
echo ""

echo "=== STEP 8: Verify Deployment ==="
echo ""
echo "solana account <PROGRAM_ID>"
echo ""
echo "# Check on Solscan:"
echo "# https://solscan.io/account/<PROGRAM_ID>"
echo ""

echo "=== STEP 9: Initialize Program ==="
echo ""
echo "# Create initialization transaction"
echo "# This depends on your program's instruction format"
echo ""

echo "=== CURRENT STATUS ==="
echo ""
echo "✗ Solana CLI: NOT INSTALLED"
echo "✗ Rust/Cargo: NOT INSTALLED"
echo "✗ Funded Wallet: UNKNOWN"
echo "✗ Program Built: NO"
echo "✗ Program Deployed: NO"
echo ""
echo "To proceed with real deployment, install required tools first."